library(celda)
library(singleCellTK)
library(lme4)
library(dplyr)
library(insight)
library(ggplot2)
library(tidyr)
library(circlize)
library(vegan)
library(RColorBrewer)
library(tidyr)
library(viridis)
library(Polychrome)
library(ComplexHeatmap)
library(data.table)
library(ggpubr)
setwd(here::here("./Scripts/Figure"))

source('.//Figure_utils.R')



### 1. Load dataset
## load sce object
op <- '../../Data'
data_sce <- readRDS(file.path(op, 'celda_Module_CellCluster_Reorder_08.rds'))

#### original module score
y <- factorizeMatrix(data_sce, type = "counts")
cell_m_counts <- y[[1]][['cell']]; cell_m_counts <- t(cell_m_counts)
colSum_sizeFactor <- colSums(t(cell_m_counts)) / 10000 
normalized_m_counts <- sweep(cell_m_counts, 1, colSum_sizeFactor, "/")
module_activity <- log2(normalized_m_counts + 1)


#### corrected module score
cr_module <- readRDS('../..//Mixed_model_output/corrected_module_score.rds')



### 2. generate UMAP using original module score
ori_mSCE <- SingleCellExperiment(assay = list(module = t(module_activity)), #
                                 rowData = NULL,
                                 colData = colData(data_sce))


ori_mSCE <- getUMAP(ori_mSCE, useAssay = 'module',
       reducedDimName = 'module_UMAP', 
       sample = NULL, minDist = 0.2, seed = 2022,
       useReducedDim = NULL, logNorm = F)

saveRDS(reducedDim(ori_mSCE, 'module_UMAP'), 
        '../../Mixed_model_output/original_module_UMAP.rds')

l <- 'study'
ori_umap <- 
plotSCEDimReduceColData(ori_mSCE, 
                        colorBy = l, reducedDimName = 'module_UMAP', 
                        clusterLabelSize = 4.5, dotSize = 0.1, labelClusters = F, 
                        colorScale = NULL, title = 'UMAP of original module') + 
  theme(
    axis.title = element_blank(),         # Change both x and y axis titles
    axis.text= element_blank(),
    axis.ticks = element_blank(),
    legend.position="none"
  ) 



### 3. load the umap generated by corrected module score
red_umap <- readRDS('../..//Mixed_model_output/corrected_module_UMAP.rds')
reducedDim(ori_mSCE, 'corrected_UMAP') <- red_umap

l <- 'study'
cor_umap <- 
plotSCEDimReduceColData(ori_mSCE, 
                        colorBy = l, reducedDimName = 'corrected_UMAP', 
                        dotSize = 0.1, 
                        colorScale = NULL, title = 'UMAP of corrected module',
                        legendSize = 5, 
                        legendTitleSize = 5, 
                        labelClusters = F) + 
  #guides(color = guide_legend(override.aes = list(size = 2))) + 
  #ggrepel::geom_text_repel() + 
  theme(
    axis.title = element_blank(),         # Change both x and y axis titles
    axis.text= element_blank(),
    axis.ticks = element_blank(),
    legend.position = c(0.9, 0.17),
    legend.background = element_blank()
    #legend.position="none"
  ) 
  



library(ggrastr)

comb_umap <- cowplot::plot_grid(ori_umap, cor_umap, nrow = 1, rel_widths = c(0.5, 0.5))
fn <- file.path('../../Figure/Figure2', 'Figure2_Ori_Correct_UMAP.pdf')
pdf(file = fn, width = 15, height = 10)
plot(rasterize(comb_umap, layers='Point', dpi=20))
dev.off()
